### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by ajatprabha** [devlup-labs/konnekt#1]
## Issue
There is currently no CI setup on this project

## Description
In order to address issues faster and continuously make sure that the code is in good health, Travis Ci or similar should be set up.

## Expected
CI build should be triggered on each push.

## Actual
No CI is set up.

### Changes [Required]
- [ ] Set up and configure Travis CI

**Comment by VagishVela** [comment]
Not sure anyone can do this. It requires at least contribute access to the repo.

**Comment by ajatprabha** [comment]
@VagishVela All the repositories here have Travis enabled, only a yml file is missing in two of the projects including this one. I saw your comment after creating a PR. You can enable Travis for the other project [here](https://github.com/devlup-labs/ignus19) after creating an issue.

**Comment by zhmurko** [comment]
I'll take look
